{"uuid": "158b3565-3083-450e-9270-bc698982fd17", "children": ["f6bb23f9-6d48-4509-a676-c911939dba6e"], "befores": [{"name": "setup", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.SessionNotCreatedException: Message: session not created\nfrom unknown error: no chrome binary at /usr/bin/google-chrome\nStacktrace:\n#0 0x608c3f19a10a <unknown>\n#1 0x608c3ee7fd20 <unknown>\n#2 0x608c3eeb5122 <unknown>\n#3 0x608c3eeb3569 <unknown>\n#4 0x608c3eeff5cb <unknown>\n#5 0x608c3eef3213 <unknown>\n#6 0x608c3eec12c5 <unknown>\n#7 0x608c3eec22ce <unknown>\n#8 0x608c3f163a4f <unknown>\n#9 0x608c3f167b36 <unknown>\n#10 0x608c3f1514b7 <unknown>\n#11 0x608c3f1682d1 <unknown>\n#12 0x608c3f13879e <unknown>\n#13 0x608c3f189098 <unknown>\n#14 0x608c3f189298 <unknown>\n#15 0x608c3f198d31 <unknown>\n#16 0x7a86522a5ac3 <unknown>\n\n", "trace": "  File \"/home/azizul/automation-4beats/venv/lib/python3.10/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"/home/azizul/automation-4beats/venv/lib/python3.10/site-packages/_pytest/fixtures.py\", line 1123, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/home/azizul/automation-4beats/venv/lib/python3.10/site-packages/_pytest/fixtures.py\", line 895, in call_fixture_func\n    fixture_result = next(generator)\n  File \"/home/azizul/automation-4beats/tests/test_checkout.py\", line 11, in setup\n    driver = webdriver.Chrome()\n  File \"/home/azizul/automation-4beats/venv/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py\", line 45, in __init__\n    super().__init__(\n  File \"/home/azizul/automation-4beats/venv/lib/python3.10/site-packages/selenium/webdriver/chromium/webdriver.py\", line 66, in __init__\n    super().__init__(command_executor=executor, options=options)\n  File \"/home/azizul/automation-4beats/venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 212, in __init__\n    self.start_session(capabilities)\n  File \"/home/azizul/automation-4beats/venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 299, in start_session\n    response = self.execute(Command.NEW_SESSION, caps)[\"value\"]\n  File \"/home/azizul/automation-4beats/venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 354, in execute\n    self.error_handler.check_response(response)\n  File \"/home/azizul/automation-4beats/venv/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1725977860070, "stop": 1725977860519}], "start": 1725977860070, "stop": 1725977860568}