{"uuid": "5d41afeb-5602-4c50-b4df-41ce2d3b38e5", "children": ["1fe112e9-98af-41ea-a11b-c61e45fffa95"], "befores": [{"name": "setup", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.SessionNotCreatedException: Message: session not created\nfrom unknown error: no chrome binary at /usr/bin/google-chrome\nStacktrace:\n#0 0x6373dda8d10a <unknown>\n#1 0x6373dd772d20 <unknown>\n#2 0x6373dd7a8122 <unknown>\n#3 0x6373dd7a6569 <unknown>\n#4 0x6373dd7f25cb <unknown>\n#5 0x6373dd7e6213 <unknown>\n#6 0x6373dd7b42c5 <unknown>\n#7 0x6373dd7b52ce <unknown>\n#8 0x6373dda56a4f <unknown>\n#9 0x6373dda5ab36 <unknown>\n#10 0x6373dda444b7 <unknown>\n#11 0x6373dda5b2d1 <unknown>\n#12 0x6373dda2b79e <unknown>\n#13 0x6373dda7c098 <unknown>\n#14 0x6373dda7c298 <unknown>\n#15 0x6373dda8bd31 <unknown>\n#16 0x792f5bf89ac3 <unknown>\n\n", "trace": "  File \"/home/azizul/automation-4beats/venv/lib/python3.10/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"/home/azizul/automation-4beats/venv/lib/python3.10/site-packages/_pytest/fixtures.py\", line 1123, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/home/azizul/automation-4beats/venv/lib/python3.10/site-packages/_pytest/fixtures.py\", line 895, in call_fixture_func\n    fixture_result = next(generator)\n  File \"/home/azizul/automation-4beats/tests/test_crud.py\", line 11, in setup\n    driver = webdriver.Chrome()\n  File \"/home/azizul/automation-4beats/venv/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py\", line 45, in __init__\n    super().__init__(\n  File \"/home/azizul/automation-4beats/venv/lib/python3.10/site-packages/selenium/webdriver/chromium/webdriver.py\", line 66, in __init__\n    super().__init__(command_executor=executor, options=options)\n  File \"/home/azizul/automation-4beats/venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 212, in __init__\n    self.start_session(capabilities)\n  File \"/home/azizul/automation-4beats/venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 299, in start_session\n    response = self.execute(Command.NEW_SESSION, caps)[\"value\"]\n  File \"/home/azizul/automation-4beats/venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 354, in execute\n    self.error_handler.check_response(response)\n  File \"/home/azizul/automation-4beats/venv/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1725977860571, "stop": 1725977861027}], "start": 1725977860571, "stop": 1725977861081}