{"uuid": "ee3cafed-1fa2-43f8-b642-a0d2319816d5", "children": ["bbbc659e-85ed-4af3-b7e7-4fd2e24eb5ba"], "befores": [{"name": "setup", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.SessionNotCreatedException: Message: session not created\nfrom unknown error: no chrome binary at /usr/bin/google-chrome\nStacktrace:\n#0 0x64eeac37610a <unknown>\n#1 0x64eeac05bd20 <unknown>\n#2 0x64eeac091122 <unknown>\n#3 0x64eeac08f569 <unknown>\n#4 0x64eeac0db5cb <unknown>\n#5 0x64eeac0cf213 <unknown>\n#6 0x64eeac09d2c5 <unknown>\n#7 0x64eeac09e2ce <unknown>\n#8 0x64eeac33fa4f <unknown>\n#9 0x64eeac343b36 <unknown>\n#10 0x64eeac32d4b7 <unknown>\n#11 0x64eeac3442d1 <unknown>\n#12 0x64eeac31479e <unknown>\n#13 0x64eeac365098 <unknown>\n#14 0x64eeac365298 <unknown>\n#15 0x64eeac374d31 <unknown>\n#16 0x74b818be5ac3 <unknown>\n\n", "trace": "  File \"/home/azizul/automation-4beats/venv/lib/python3.10/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"/home/azizul/automation-4beats/venv/lib/python3.10/site-packages/_pytest/fixtures.py\", line 1123, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/home/azizul/automation-4beats/venv/lib/python3.10/site-packages/_pytest/fixtures.py\", line 895, in call_fixture_func\n    fixture_result = next(generator)\n  File \"/home/azizul/automation-4beats/tests/test_navigation.py\", line 9, in setup\n    driver = webdriver.Chrome()\n  File \"/home/azizul/automation-4beats/venv/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py\", line 45, in __init__\n    super().__init__(\n  File \"/home/azizul/automation-4beats/venv/lib/python3.10/site-packages/selenium/webdriver/chromium/webdriver.py\", line 66, in __init__\n    super().__init__(command_executor=executor, options=options)\n  File \"/home/azizul/automation-4beats/venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 212, in __init__\n    self.start_session(capabilities)\n  File \"/home/azizul/automation-4beats/venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 299, in start_session\n    response = self.execute(Command.NEW_SESSION, caps)[\"value\"]\n  File \"/home/azizul/automation-4beats/venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 354, in execute\n    self.error_handler.check_response(response)\n  File \"/home/azizul/automation-4beats/venv/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1725977861627, "stop": 1725977862087}], "start": 1725977861627, "stop": 1725977862135}