{"uuid": "22b8233b-8750-41b3-809e-37ba93947d6b", "children": ["5e2420e4-be0b-4f65-b0a2-c8ba5c742c9f"], "befores": [{"name": "setup", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.SessionNotCreatedException: Message: session not created\nfrom unknown error: no chrome binary at /usr/bin/google-chrome\nStacktrace:\n#0 0x59c16460210a <unknown>\n#1 0x59c1642e7d20 <unknown>\n#2 0x59c16431d122 <unknown>\n#3 0x59c16431b569 <unknown>\n#4 0x59c1643675cb <unknown>\n#5 0x59c16435b213 <unknown>\n#6 0x59c1643292c5 <unknown>\n#7 0x59c16432a2ce <unknown>\n#8 0x59c1645cba4f <unknown>\n#9 0x59c1645cfb36 <unknown>\n#10 0x59c1645b94b7 <unknown>\n#11 0x59c1645d02d1 <unknown>\n#12 0x59c1645a079e <unknown>\n#13 0x59c1645f1098 <unknown>\n#14 0x59c1645f1298 <unknown>\n#15 0x59c164600d31 <unknown>\n#16 0x733aec15cac3 <unknown>\n\n", "trace": "  File \"/home/azizul/automation-4beats/venv/lib/python3.10/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"/home/azizul/automation-4beats/venv/lib/python3.10/site-packages/_pytest/fixtures.py\", line 1123, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/home/azizul/automation-4beats/venv/lib/python3.10/site-packages/_pytest/fixtures.py\", line 895, in call_fixture_func\n    fixture_result = next(generator)\n  File \"/home/azizul/automation-4beats/tests/test_cart.py\", line 8, in setup\n    driver = webdriver.Chrome()\n  File \"/home/azizul/automation-4beats/venv/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py\", line 45, in __init__\n    super().__init__(\n  File \"/home/azizul/automation-4beats/venv/lib/python3.10/site-packages/selenium/webdriver/chromium/webdriver.py\", line 66, in __init__\n    super().__init__(command_executor=executor, options=options)\n  File \"/home/azizul/automation-4beats/venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 212, in __init__\n    self.start_session(capabilities)\n  File \"/home/azizul/automation-4beats/venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 299, in start_session\n    response = self.execute(Command.NEW_SESSION, caps)[\"value\"]\n  File \"/home/azizul/automation-4beats/venv/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 354, in execute\n    self.error_handler.check_response(response)\n  File \"/home/azizul/automation-4beats/venv/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1725977859502, "stop": 1725977859942}], "start": 1725977859502, "stop": 1725977860067}